name: Push

on:
  push:
    branches:
      - main
      - ethers-v6

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: test

    uses: ./.github/workflows/release.yml
    secrets: inherit
