name: Jest Test Suite

on:
  pull_request:
    paths:
      - src/**
      - test/**
      - package.json
      - yarn.lock
  workflow_call:
    secrets:
      WS_RPC_URL:
        required: true
      HTTP_RPC_URL:
        required: true

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Jest test suite
        run: yarn test
        env:
          WS_RPC_URL: ${{ secrets.WS_RPC_URL }}
          HTTP_RPC_URL: ${{ secrets.HTTP_RPC_URL }}
